I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/rpyfunction/crossdialog.rpy", line 39, in script
    return
Exception: Could not find return label ('game/script.rpy', 1697703917, 1520).

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/rpyfunction/crossdialog.rpy", line 39, in script
    return
  File "E:\1\gamegenerator\renpy-8.1.3-sdk\renpy\ast.py", line 1801, in execute
    next_node(renpy.game.context().lookup_return(pop=True))
  File "E:\1\gamegenerator\renpy-8.1.3-sdk\renpy\execution.py", line 741, in lookup_return
    raise Exception("Could not find return label {!r}.".format(self.return_stack[-1]))
Exception: Could not find return label ('game/script.rpy', 1697703917, 1520).

Windows-10-10.0.22621 AMD64
Ren'Py 8.1.3.23091805
Skythread 1.0
Thu Oct 19 17:11:32 2023
